# Generated by Django 4.1.1 on 2022-09-16 08:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricehistory",
            name="end_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="pricehistory",
            name="start_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
