# Generated by Django 4.1.1 on 2022-09-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_pricehistory_end_date_pricehistory_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricehistory",
            name="end_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="pricehistory",
            name="start_date",
            field=models.DateTimeField(),
        ),
    ]
